### ISSUE TITLE
AttributeError: 'LinearSVC' object has no attribute 'classes_'

### ISSUE THREAD

**Issue by oleg-savko** [FraPochetti/ImageTextRecognition#1]
Hi! I have a problem to run your project.
Do you know, what is the problem?

Traceback (most recent call last):
  File "/Users/aleh/Development/samples/python/ImageTextRecognition/main.py", line 22, in <module>
    maybe_text = user.select_text_among_candidates('/Users/aleh/Development/samples/python/ImageTextRecognition/linearsvc-hog-fulltrain2-90.pickle')
  File "/Users/aleh/Development/samples/python/ImageTextRecognition/userimageski.py", line 105, in select_text_among_candidates
    is_text = model.predict(self.candidates['flattened'])
  File "/Library/Python/2.7/site-packages/sklearn/utils/metaestimators.py", line 37, in <lambda>
    out = lambda _args, *_kwargs: self.fn(obj, _args, *_kwargs)
  File "/Library/Python/2.7/site-packages/sklearn/pipeline.py", line 204, in predict
    return self.steps[-1][-1].predict(Xt)
  File "/Library/Python/2.7/site-packages/sklearn/linear_model/base.py", line 273, in predict
    return self.classes_[indices]
AttributeError: 'LinearSVC' object has no attribute 'classes_'

**Comment by vinothkumar91** [comment]
Traceback (most recent call last):
  File "/Users/ThomasInnovation/PycharmProjects/TextRecognition/main.py", line 14, in <module>
    maybe_text = user.select_text_among_candidates('/Users/ThomasInnovation/PycharmProjects/TextRecognition/linearsvc-hog-fulltrain2-90.pickle')
  File "/Users/ThomasInnovation/PycharmProjects/TextRecognition/userimageski.py", line 103, in select_text_among_candidates
    is_text = model.predict(self.candidates['flattened'])
  File "/Library/Python/2.7/site-packages/sklearn/utils/metaestimators.py", line 37, in <lambda>
    out = lambda _args, *_kwargs: self.fn(obj, _args, *_kwargs)
  File "/Library/Python/2.7/site-packages/sklearn/pipeline.py", line 204, in predict
    return self.steps[-1][-1].predict(Xt)
  File "/Library/Python/2.7/site-packages/sklearn/linear_model/base.py", line 273, in predict
    return self.classes_[indices]
AttributeError: 'LinearSVC' object has no attribute 'classes_'

**Comment by zhuyuecai** [comment]
I have the same issue as well

**Comment by thierrydecae** [comment]
me too :-(

**Comment by SarfraazMsa** [comment]
pip install scikit-learn==0.15.2 ...it will work

**Comment by samar5yadav** [comment]
same problem

**Comment by ronair01** [comment]
@SarfraazMsa - Thanks a lot! That worked for me!

**Comment by SarfraazMsa** [comment]
great then @ronair01

**Comment by Farhan248** [comment]
I had issues unpickling the pickle files so I set encoding to latin1 when loading. However, this provided the following error:

Traceback (most recent call last):
  File "C:\Users\Elitebook\Desktop\ImageTextRecognition-master\ImageTextRecognition-master\main.py", line 29, in <module>
    classified = user.classify_text(os.path.join(dir_file, 'linearsvc-hog-fulltrain36-90.pickle'))
  File "C:\Users\Elitebook\Desktop\ImageTextRecognition-master\ImageTextRecognition-master\userimageski.py", line 129, in classify_text
    which_text = model.predict(self.to_be_classified['flattened'])
  File "C:\Users\Elitebook\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sklearn\pipeline.py", line 150, in predict
    return self.steps[-1][-1].predict(Xt)
  File "C:\Users\Elitebook\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sklearn\linear_model\base.py", line 215, in predict
    scores = self.decision_function(X)
  File "C:\Users\Elitebook\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sklearn\linear_model\base.py", line 196, in decision_function
    % (X.shape[1], n_features))
ValueError: X has 0 features per sample; expecting 3920

I assume this is because the code is unable to detect the objects as text since the "Objects Containing Text Detected" page is empty. Can anyone help me out here?

**Comment by suhasdatascientist** [comment]
Traceback (most recent call last):

  File "<ipython-input-48-40084badaebb>", line 1, in <module>
    runfile('/home/king/Downloads/pooja project/ImageTextRecognition-master/main.py', wdir='/home/king/Downloads/pooja project/ImageTextRecognition-master')

  File "/home/anaconda3/envs/py27/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/home/anaconda3/envs/py27/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 94, in execfile
    builtins.execfile(filename, *where)

  File "/home/king/Downloads/pooja project/ImageTextRecognition-master/main.py", line 22, in <module>
    maybe_text = user.select_text_among_candidates('linearsvc-hog-fulltrain2-90.pickle')

  File "userimageski.py", line 103, in select_text_among_candidates
    is_text = model.predict(self.candidates['flattened'])

  File "/home/anaconda3/envs/py27/lib/python2.7/site-packages/sklearn/utils/metaestimators.py", line 35, in __get__

AttributeError: '_IffHasAttrDescriptor' object has no attribute 'get_attribute'

**Comment by FraPochetti** [comment]
Hi guys, sorry but I have not been working on this project for years. The code base is really old and completely outdated. Not really sure how to help here.

**Comment by suhasdatascientist** [comment]
now that issue has been resolved by downgrading scikit learn to 0.15.1 version, but still the characters that recognized from the same image for the same code is different, where exaclty the problem will be
![t1](https://user-images.githubusercontent.com/32155222/46205328-d80dbb00-c33d-11e8-8967-284c92fcf8df.png)

**Comment by rchavezj** [comment]
> pip install scikit-learn==0.15.2 ...it will work

Since downgrading is the solution, I assume we need to change a certain syntax for the newest version of scikit-learn correct?

**Comment by SarfraazMsa** [comment]
yes

> > pip install scikit-learn==0.15.2 ...it will work
> 
> Since downgrading is the solution, I assume we need to change a certain syntax for the newest version of scikit-learn correct?

yes @rchavezj
