### ISSUE TITLE
AttributeError: 'LinearSVC' object has no attribute 'classes_'

### ISSUE THREAD

**Issue by vinothkumar91** [FraPochetti/ImageTextRecognition#2]
Traceback (most recent call last):
  File "/Users/ThomasInnovation/PycharmProjects/TextRecognition/main.py", line 14, in <module>
    maybe_text = user.select_text_among_candidates('/Users/ThomasInnovation/PycharmProjects/TextRecognition/linearsvc-hog-fulltrain2-90.pickle')
  File "/Users/ThomasInnovation/PycharmProjects/TextRecognition/userimageski.py", line 103, in select_text_among_candidates
    is_text = model.predict(self.candidates['flattened'])
  File "/Library/Python/2.7/site-packages/sklearn/utils/metaestimators.py", line 37, in <lambda>
    out = lambda _args, *_kwargs: self.fn(obj, _args, *_kwargs)
  File "/Library/Python/2.7/site-packages/sklearn/pipeline.py", line 204, in predict
    return self.steps[-1][-1].predict(Xt)
  File "/Library/Python/2.7/site-packages/sklearn/linear_model/base.py", line 273, in predict
    return self.classes_[indices]
AttributeError: 'LinearSVC' object has no attribute 'classes_'

**Comment by SarfraazMsa** [comment]
pip install scikit-learn==0.15.2 ...it will work
