### ISSUE TITLE
convnet error

### ISSUE THREAD

**Issue by riturajsoni** [FraPochetti/ImageTextRecognition#3]
Traceback (most recent call last):
  File "main.py", line 21, in <module>
    maybe_text = user.select_text_among_candidates('/home/rituraj/ImageTextRecognition-master/linearsvc-hog-fulltrain2-90.pickle')
  File "/home/rituraj/ImageTextRecognition-master/userimageski.py", line 100, in select_text_among_candidates
    model = cPickle.load(fin)
  File "/home/rituraj/ImageTextRecognition-master/data.py", line 21, in <module>
    from nolearn.convnet import ConvNeNetFeatures
ImportError: No module named convnet

Hi I am getting the above error ply help to resolve it.

**Comment by nitish11** [comment]
The package nolearn has been upgraded, and nolearn.convnet is deprecated. [Ref](https://pythonhosted.org/nolearn/decaf.html#nolearn.decaf.ConvNetFeatures)

Use the below line to fix the issue.

`from nolearn.decaf import ConvNeNetFeatures`

To install the latest nolearn package, follow the below lines.

```
pip install -r https://raw.githubusercontent.com/dnouri/nolearn/master/requirements.txt
pip install git+https://github.com/dnouri/nolearn.git@master#egg=nolearn==0.7.git
```

**Comment by yu-changqian** [comment]
There is a small error:
```
from nolearn.decaf import ConvNetFeatures
```

**Comment by Makogan** [comment]
Where should I add:
from nolearn.decaf import ConvNetFeatures

**Comment by adamzjw** [comment]
looks like it's caused by mismatch of the nolearn version from the pickle file.
Use version 0.5 will fix this.
