### ISSUE TITLE
ocr-config . and training

### ISSUE THREAD

**Issue by MyraBaba** [FraPochetti/ImageTextRecognition#8]
I have below errors:
```

Traceback (most recent call last):
  File "/Users/alpullu/PycharmProjects/ImageTextRecognition/main.py", line 42, in <module>
    data = OcrData('ocr-config.py')
  File "/Users/alpullu/PycharmProjects/ImageTextRecognition/data.py", line 55, in __init__
    self.load()
  File "/Users/alpullu/PycharmProjects/ImageTextRecognition/data.py", line 185, in load
    print 'Loaded {} images each {} pixels'.format(self.ocr['images'].shape[0], self.img_size)
TypeError: 'Pipeline' object has no attribute '__getitem__'

```

`    data = OcrData('ocr-config.py')
`

can you give a full example :) for training and ocr-config parameters and their respective files ? 

thx

**Comment by chitransh1998** [comment]
Hey I needed the same help for my project.
@MyraBaba  did you get any replies for the same?
If yes then please help me with it.
Thankyou:)

**Comment by MyraBaba** [comment]
unfortunately didn't get any feedback.
