### ISSUE TITLE
No such file or directory: 'lao.jpg'

### ISSUE THREAD

**Issue by ankit-srivast-v** [FraPochetti/ImageTextRecognition#9]
Traceback (most recent call last):
  File "C:\Users\500040184\My Documents\LiClipse Workspace\major1\src\ImageTextRecognition-master\main.py", line 13, in <module>
    user = UserData('lao.jpg')
  File "C:\Users\500040184\My Documents\LiClipse Workspace\major1\src\ImageTextRecognition-master\userimageski.py", line 25, in __init__
    self.image = imread(image_file, as_grey=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\skimage\io\_io.py", line 61, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\skimage\io\manage_plugins.py", line 211, in call_plugin
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\skimage\io\_plugins\pil_plugin.py", line 35, in imread
    with open(fname, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'lao.jpg'

please guide me where to place the jpg file I am using liclipse

**Comment by alexleech** [comment]
Seems like you can just replace it with any picture you want
